NethServer/comps

- nethserver-groups.xml.in
Add optional php packages to nethserver-web group. Refs #375
> Add optional php packages to nethserver-web group

- nethserver-groups.xml.in
> Add nethserver-diagtools to iso group

- nethserver-groups.xml.in
- po/comps.pot
- po/cs_CZ.po
- po/el.po
- po/es.po
- po/fr.po
- po/hu.po
- po/it.po
- po/lt.po
- po/nl.po
- po/pt.po
- po/pt_BR.po
- po/ro.po
- po/ru.po
- po/sl.po
- po/sr.po
- po/sv.po
- po/tr.po
See also
http://community.nethserver.org/t/help-me-to-translate-nethserver-in-romanian-language/6754/23
> Add Romanian language pack

- nethserver-groups.xml.in
- po/comps.pot
> Add nethserver-subscription group

- nethserver-groups.xml.in
> Alternative mail server implementation (beta)

- nethserver-groups.xml.in
> Rename nethserver-virtualhosts package

- nethserver-groups.xml.in
> Install mail2 module as new default

- nethforge-groups.xml.in
> Remove webvirtmgr

- nethserver-groups.xml.in
https://github.com/NethServer/dev/issues/5489
@DavidePrincipi I cannot add you as reviewer
> Create the nethserver-fail2ban group comps

- nethserver-groups.xml.in
Delete also all obsolete groups.
NethServer/dev#5589
> Replace mail2 with mail

- .tx/config
- nethserver-groups.xml.in
- po/comps.pot
- po/cs.po
- po/de.po
- po/el.po
- po/es.po
- po/fr.po
- po/hu.po
- po/it.po
- po/nl.po
- po/pt.po
- po/pt_BR.po
- po/ru.po
- po/sr.po
- po/sv.po
- po/tr.po
- Configure for Transifex translations
NethServer/dev#5564
>  New Upgrade tool (beta) module 

- nethserver-groups.xml.in
- po/comps.pot
> Add cockpit group

- arm-nethforge-groups.xml.in
- arm-nethserver-groups.xml.in
- scripts/upload.sh
Initial comps for arm. 
I tried to upload the arm-nethserver-groups.xml, seems i do not have the permission to do this..
```
$ echo -e "cd nscom/7.6.1810/\nput arm-nethserver-groups.xml arm-updates-groups.xml"  | sftp -b - packages.nethserver.org
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
Couldn't read packet: Connection reset by peer
```
> Arm integration

- nethforge-groups.xml.in
- po/comps.pot
> nethforge: add Collabora Online

- po/comps.pot
> Update comps for netdata

- po/comps.pot
- updates-groups.xml.in
> Add nethserver-dante

- nethforge-groups.xml.in
- po/comps.pot
- updates-groups.xml.in
See also https://community.nethserver.org/t/uncategorized-packages/13355
> Fix collabora category and promote cockpit

- updates-groups.xml.in
https://github.com/NethServer/dev/issues/5831
> Add nethserver-cockpit to ISO

- updates-groups.xml.in
Relative to issue https://github.com/NethServer/dev/issues/5912
Relative to PR https://github.com/NethServer/nethserver-httpd/pull/56
create yum group to install rh-php72 and rh-php71
> Yum groups for rh-php72 and rh-php71

- updates-groups.xml.in
Reverts NethServer/comps#33
Obsoleted by
- https://github.com/NethServer/nethserver-rh-php72-php-fpm/pull/1
- https://github.com/NethServer/nethserver-rh-php71-php-fpm/pull/2
NethServer/dev#5912
> Revert "Yum groups for rh-php72 and rh-php71"

- nethforge-groups.xml.in
- po/comps.pot
> Move hotsync to nethforge

- nethforge-groups.xml.in
Added nethserver-mssql group id into NethForge package list.
Refer to https://github.com/NethServer/dev/issues/6078
> comps. add nethserver-mssql group

- po/comps.pot
- updates-groups.xml.in
Dante report have been proved good.
> dante report: remove beta tag

- po/comps.pot
- updates-groups.xml.in
> Add nethserver-blacklist group

- updates-groups.xml.in
Cockpit is ready for prime time
NethServer/dev#6117
> Remove beta tag from Cockpit

- updates-groups.xml.in
p3scan is now officially deprecated
NethServer/dev#6117
> Hide p3scan group

- nethforge-groups.xml.in
Release of nethserver-business
> forge: add business package

- nethforge-groups.xml.in
See https://community.nethserver.org/t/business-cube-nts-and-what-is-it-doing-in-nethserver/16094/
> forge: improve business description

- po/comps.pot
- updates-groups.xml.in
> Remove httpd-admin from ISO group

- updates-groups.xml.in
> Add nethserver-netdata to ISO group

- po/cs_CZ.po
- po/de.po
- po/el.po
- po/es.po
- po/fr.po
- po/hu.po
- po/it.po
- po/lt.po
- po/nl.po
- po/pt.po
- po/pt_BR.po
- po/ro.po
- po/ru.po
- po/sl.po
- po/sr.po
- po/sv.po
- po/tr.po
Update translations
See also https://community.nethserver.org/t/typo-error-into-nextcloud-module-italian-description/19021
> Pull translations

- nethforge-groups.xml.in
- po/comps.pot
https://github.com/NethServer/dev/issues/6627
> nethserver-roundcubemail-next in nethforge

- .github/workflows/build.yml
Updated `python-libxml2` to `python3-libxml2`
> Fixed GitHub Action

- updates-groups.xml.in
Display the migration package inside the UI
Card: https://trello.com/c/0SsoXN5P/172-release-checklist
> comps: add nethserver-firewall-migration
